# Generated by Django 2.1.7 on 2021-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDP_ap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_com', models.IntegerField(blank=True, null=True)),
                ('years_of_ex', models.IntegerField(blank=True, null=True)),
                ('total_clients', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProtModel',
        ),
    ]
